.Dd March  3, 2025
.Dt ARTICLE 7
.Os naki
.
.Bq #@! INTRO
.Sh NAME
.Nm CLA
.Nd быстрый сумматор
.
.Sh SYNOPSIS
.Nm
.Nd Carry-lookahead Adder
.
.Sh DESCRIPTION
.Ss RCA
.Bq #@! RCADIAG
Думаю,
вы представляете,
как работает
.Dq обычный
сумматор:
биты суммируемых чисел
соответственно складываются,
а
.Sy carry
.Pq бит переноса
- переносится последовательно,
справа налево,
от наименее
к наиболее значащему биту.
.
.Pp
Ну,
казалось бы,
отличный метод!
Однако у него есть один
совсем небольшой
недостаток:
он медленный.
Очень.
Чтобы сложить 32 битное число
вам придется подождать задержку
от 32 сумматоров!
.
.Ss Переход
.Bq #@! TRANSITION
Учитывая большое количество сложений,
происходящее внутри компьютера,
можно понять,
что так дело не пойдет.
Нужен какой-то способ,
чтобы сразу посчитать
этот carry.
.
.Ss CLA
.Bq #@! CLA
Ну и,
оказывается,
такой способ есть.
Есть так называемые
.Nm
.Pq Carry-lookahead Adder
сумматоры.
.
.Ss Метод работы
.Nm
в своей идее
имеет понятия
.Sy генерации
и
.Sy передачи
бита переноса.
Сумма
двух битов
.Sy генерирует
перенос
только в том случае,
если они оба равны 1.
.Bq #@! AND
Это соответствует
функции
.Dq логического и .
Сумма передает значение,
когда уже установлен carry,
а также хотя бы 1 бит в сумме
равен 1.
.Bq #@! OR
Это соответствует
функции
.Dq логического или .
Также
.Bq #@! XOR
.Nm
допускает логику
.Dq исключающего или
для пределения
передачи carry.
.
.Pp
.Bq #@! CARRY
Получается,
что чтобы узнать
carry для суммы битов
.Ql Ai
м
.Ql Bi ,
нужно провести
операцию
.Dq логического или
между функцией
вычисления генерации,
и функцией вычисления передачи,
помноженной на
предыдущий carry.
.Bq #@! CARRY1
Несложно догадаться,
что можно заменить предыдущий carry
на такую же формулу,
заканчивая рекурсию
на наименее значащем бите.
.Bq #@! CARRYOPTIMIZED
Используя законы
булевой алгебры
можно упростить получившееся выражение,
сделав схему простой и быстрой.
.Bq #@! CLADIAG
На данной картинке
можно увидеть,
как выглядит
схема CLA сумматора.
.
.Ss Заключение
.Bq #@! OUTRO
Итак,
это было приблизительное объяснение
работы CLA сумматора.
Надеюсь оно помогло вам
разобраться с ним получше.
Для более подробного описания
советую посмотреть статью
на википедии
по этой теме.
.
.Sh AUTHORS
CC0 - No Rights Reserved
.Pp
.An Nakidai Perumenei Aq Mt nakidai@disroot.org
.
.Pp
Здесь были использованы материалы:
.Bl -bullet
.It Схема RCA
By
.An Cburnett
- Own work,
.Ql CC BY-SA 3.0 ,
.Lk https://commons.wikimedia.org/w/index.php?curid=1477488
.
.It Схема CLA
By
.An Cburnett
- This W3C-unspecified vector image
was created with Inkscape,
.Ql CC BY-SA 3.0 ,
.Lk https://commons.wikimedia.org/w/index.php?curid=1477525
.
.It Эмодзи лисенка
Copyright 2019
.An Feuerfuchs Aq Mt me@feuerfuchs.dev
.Pq Lk https://www.feuerfuchs.dev/ ,
.Ql Apache-2.0
.El
