.Dd March  3, 2025
.Dt README 7
.Os naki
.
.Sh NAME
.Nm CLA
.Nd быстрый сумматор
.
.Sh SYNOPSIS
.Nm
.Nd Carry-lookahead Adder
.
.Sh DESCRIPTION
Описание работы
.Nm
сумматора.
.
.Pp
Видео можно найти
на
.Lk https://youtu.be/yyt4rzfY8ng YouTube .
.
.Pp
Чтобы просмотреть презентацию у себя,
необходимо устноавить
.Lk https://tools.suckless.org/sent/ sent ,
и через него запустить
.Ql presentation .
.
.Sh AUTHORS
CC0 - No Rights Reserved
.Pp
.An Nakidai Perumenei Aq Mt nakidai@disroot.org
.
.Pp
Здесь были использованы материалы:
.Bl -bullet
.It Схема RCA
By
.An Cburnett
- Own work,
.Ql CC BY-SA 3.0 ,
.Lk https://commons.wikimedia.org/w/index.php?curid=1477488
.
.It Схема CLA
By
.An Cburnett
- This W3C-unspecified vector image
was created with Inkscape,
.Ql CC BY-SA 3.0 ,
.Lk https://commons.wikimedia.org/w/index.php?curid=1477525
.
.It Эмодзи лисенка
Copyright 2019
.An Feuerfuchs Aq Mt me@feuerfuchs.dev
.Pq Lk https://www.feuerfuchs.dev/ ,
.Ql Apache-2.0
.El
